---
title: "Interpretability Examples"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

First we load in the crabs data set.
This contains physical measurements of several species of crabs collected at Fremantle, West Australia.

```{r, echo = F, message = F}
library(MASS)
library(data.table)
library(ggplot2)
library(interpret)
library(Rforestry)

# source("predictor.R")
# source("interpret.R")
source("~/Dropbox/interpretability_sandbox/R/plotter.R")
set.seed(491)

data <- MASS::crabs
levels(data$sex) <- list(Male = "M", Female = "F")
levels(data$sex) <- list(Orange = "O", Blue = "B")
colnames(data) <- c("Species","Sex","Index","Frontal Lobe",
                    "Rear Width", "Carapace Length","Carapace Width","Body Depth")

```



```{r}
# try with different dataset
set.seed(491)
test_ind <- sample(1:nrow(data), nrow(data)%/%5)
train_reg <- data[-test_ind,]
test_reg <- data[test_ind,]

# Train a random forest on the data set
forest <- forestry(x=train_reg[,-which(names(train_reg)=="Carapace Width")],
                   y=train_reg[,which(names(train_reg)=="Carapace Width")])

# Create a predictor wrapper for the forest
# this allows us to use a standard wrapper for querying any 
# trained estimator
forest_predictor <- Predictor$new(model = forest, 
                                  data=train_reg, 
                                  y="Carapace Width",
                                  task = "regression")
```


```{r}
# Now given a predictor object, we can create an interpretor class
forestinterpret <- Interpreter$new(predictor = forest_predictor)

print(forestinterpret)
# Check to see that the specified functions are behaving
#print(forestinterpret$functions.1d$`Body Depth`(1))

```

```{r}

# check plotter wrapper
forestplot <- Plotter$new(forestinterpret, features = c("Frontal Lobe"),
                          features.2d = data.frame(col1 = c("Frontal Lobe", "Frontal Lobe"),
                                                   col2 = c("Species", "Sex")))

plots <- plot.Plotter(forestplot)
plots[[1]]
plots[[2]]
plots[[3]]
```


```{r}
# test functions for the plotter
forestplot$center.at$`Frontal Lobe`
forestplot$grid.points$`Frontal Lobe`

set.center.at(forestplot, "Frontal Lobe", 2) # for numeric
forestplot$center.at$`Frontal Lobe`
set.grid.points(forestplot, "Frontal Lobe", c(1.2,3.9,1.3, 1.4))
forestplot$grid.points$`Frontal Lobe`

```

